### ISSUE TITLE
Repeatedly being asked to install 1.26

### ISSUE THREAD

**Issue by timur-tabi** [TheSpaghettiDetective/OctoPrint-TheSpaghettiDetective#68]
I got a notification to install the 1.26 update, so I did.  The server rebooted, and I was once again asked to install 1.26.  I figured maybe the install didn't quite go through, so I said yes again.  The server rebooted, and I was asked a third time to install 1.26.  This time I clicked "ignore", but I'm quite certain that this process would have repeated indefinitely otherwise.

**Comment by kennethjiang** [comment]
Thank you for reporting this problem to us. It was caused by the name change of our plugin.

There is no easy way to "fix" it. We just implemented a workaround to "force" OctoPrint to adopt the new name. When you see the prompt of upgrade to version 1.3.0, please do so, and the problem should be solved. Let me know if you still have the same problem after upgrading to 1.3.0.

**Comment by RaymondHimle** [comment]
@timur-tabi Has this been resolved?

**Comment by timur-tabi** [comment]
I guess so.  I've updated the plugin a few times now and have not had the problem.

On a side note, could you please rename the plugin back to its previous name?  "Access Anywhere - The Spaghetti Detective" is long and obnoxious.  I know why you did it, but I don't like it.  Nothing wrong with just calling it "Spaghetti Detective".
